apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  selector:
    app: jenkins
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30010  # Choose a node port number
    - name: agent
      protocol: TCP
      port: 50000
      targetPort: 50000
      nodePort: 30011  # Choose another node port number